#!/bin/bash
#
# Copyright 2019 Vladimir Botka <vbotka@gmail.com>
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
# 1. Redistributions of source code must retain the above copyright
# notice, this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright
# notice, this list of conditions and the following disclaimer in the
# documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#

version=1.0.0

HBORDER=`cat ~/.DISPLAY_MOUSE_HBORDER`
LBORDER=${HBORDER% *}
RBORDER=${HBORDER#* }
#echo $LBORDER $RBORDER

DELTA=`cat ~/.DISPLAY_MOUSE_DELTA`
XDELTA=${DELTA% *}
#echo $XDELTA

POSITION=`cat ~/.DISPLAY_MOUSE_POSITION`
X=${POSITION% *}
Y=${POSITION#* }
#echo $X $Y

X=$(($X-$XDELTA))
if (( X < LBORDER )); then
    X=$LBORDER
fi

#echo $X $Y
echo $X $Y > ~/.DISPLAY_MOUSE_POSITION
xdotool mousemove $X $Y

# EOF
