#!/bin/bash
#
VERSION="0.1"

OBEXHCI=0
# MYPHONE=<BLUETOOTH-ADDRESS>
MYFOLDER=DCIM/100ANDRO
FILES=$(obexftp -d $OBEXHCI -b $MYPHONE -C $MYFOLDER -l | xmlstarlet sel -T -t -m //file/@name -v . -n)
for i in $FILES; do
    obexftp -d $OBEXHCI -b $MYPHONE -C $MYFOLDER -g $i
done
