#!/bin/bash
#set -x

HCI=$OBEXHCI
KEEPASS_SRC=/home/$USER/keepassx
KEEPASS_DEST=keepass
KEEPASS_DB=database.kdbx

DEVICE="MY$1"
BTADDRESS=${!DEVICE}
#echo "BT address of $DEVICE: $BTADDRESS"
#exit

CHANNEL=$(sdptool browse $BTADDRESS | grep -A 20 "OBEX FTP" | grep -m1 Channel | cut -f 2 -d ":")
CHANNEL="${CHANNEL:-0}"
printf -v CHANNEL '%d\n' $CHANNEL 2>/dev/null
((! $CHANNEL)) && printf "$0: OBEX FTP not available.\n" && exit 1
sleep 1
obexftp -d $HCI -b $BTADDRESS -B $CHANNEL -c $KEEPASS_DEST -k $KEEPASS_DB
sleep 1
obexftp -d $HCI -b $BTADDRESS -B $CHANNEL -c $KEEPASS_DEST -p $KEEPASS_SRC/$KEEPASS_DB

# EOF
