#!/bin/bash
for i in "$@"; do
target=`echo "$i" | sed 's/ /_/g'`;         # remove "space"
#target=`echo "$target" | sed 's/%20/_/g'`;  # change "space" to "_"
target=`echo "$target" | sed 's/(//g'`;     # remove "("
target=`echo "$target" | sed 's/)//g'`;     # remove ")"
#target=`echo "$target" | sed 's/,//g'`;     # remove ","
#target=`echo "$target" | sed 's/:/-/g'`;    # change ":" to "-"
target=`echo "$target" | sed 's/@//g'`;     # remove "@"
target=`echo "$target" | sed 's/[^A-Za-z0-9._-]/_/g'`;
target=`echo "$target" | iconv -f latin1 -t ascii//TRANSLIT`;
echo "Renaming '$i' to '$target'";
mv "$i" "$target";
done
